# S-Dot EDA

In [2]:
import pandas as pd

df = pd.read_csv("../data/S-DoT_NATURE_2026.06.22-06.28.csv", encoding="cp949")
print(f"데이터프레임 크기: {df.shape[0]} rows, {df.shape[1]} columns")
print(df.info())
df.head(5)

데이터프레임 크기: 115114 rows, 58 columns
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 115114 entries, ('SDOT001', 'OC3CL200011', '2026-06-22_00:07:00', 'parks', 'Seoul_Grand_Park', 'valet_parking1') to ('SDOT001', 'V02Q1941015', '2026-06-28_23:07:00', 'residential_area', 'Seongdong-gu', 'Seongsu1ga1(il)-dong')
Data columns (total 58 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   모델번호            106490 non-null  float64
 1   시리얼             106490 non-null  float64
 2   측정시간            106489 non-null  float64
 3   지역              91704 non-null   float64
 4   자치구             92644 non-null   float64
 5   행정동             93446 non-null   float64
 6   온도 최대(℃)        5639 non-null    float64
 7   온도 평균(℃)        5639 non-null    float64
 8   온도 최소(℃)        5639 non-null    float64
 9   습도 최대(%)        5639 non-null    float64
 10  습도 평균(%)        5639 non-null    float64
 11  습도 최소(%)        5639 non-null    float64
 12  풍속 최대(m/s)      91069 non-null   float64
 13  풍속 평균(m/s)      91069 non-null   float64
 14  풍속 최소(m/s)      91069 non-null   float64
 15  풍향 최대(m/s)      91885 non-null   float64
 16  풍향 평균(m/s)      91885 non-null   float64
 17  풍향 최소(m/s)      91885 non-null   float64
 18  조도 최대(lux)      108164 non-null  float64
 19  조도 평균(lux)      108164 non-null  float64
 20  조도 최소(lux)      108164 non-null  float64
 21  자외선 최대(UV)      86740 non-null   float64
 22  자외선 평균(UV)      86740 non-null   float64
 23  자외선 최소(UV)      86740 non-null   float64
 24  소음 최대(dB)       86740 non-null   float64
 25  소음 평균(dB)       86740 non-null   float64
 26  소음 최소(dB)       86740 non-null   float64
 27  진동(x) 최대(mm/s)  86740 non-null   float64
 28  진동(x) 평균(mm/s)  86740 non-null   float64
 29  진동(x) 최소(mm/s)  86740 non-null   float64
 30  진동(y) 최대(mm/s)  3679 non-null    float64
 31  진동(y) 평균(mm/s)  3679 non-null    float64
 32  진동(y) 최소(mm/s)  3679 non-null    float64
 33  진동(z) 최대(mm/s)  7943 non-null    float64
 34  진동(z) 평균(mm/s)  7943 non-null    float64
 35  진동(z) 최소(mm/s)  7943 non-null    float64
 36  흑구온도 최대(℃)      7943 non-null    float64
 37  흑구온도 평균(℃)      7943 non-null    float64
 38  흑구온도 최소(℃)      7943 non-null    float64
 39  이산화질소 최대(ppm)   4505 non-null    float64
 40  이산화질소 평균(ppm)   4558 non-null    float64
 41  이산화질소 최소(ppm)   4558 non-null    float64
 42  일산화탄소 최대(ppm)   4525 non-null    float64
 43  일산화탄소 평균(ppm)   4525 non-null    float64
 44  일산화탄소 최소(ppm)   4525 non-null    float64
 45  이산화황 최대(ppm)    4525 non-null    float64
 46  이산화황 평균(ppm)    4525 non-null    float64
 47  이산화황 최소(ppm)    4525 non-null    float64
 48  암모니아 최대(ppm)    2934 non-null    float64
 49  암모니아 평균(ppm)    2934 non-null    float64
 50  암모니아 최소(ppm)    2934 non-null    float64
 51  황화수소 최대(ppm)    115114 non-null  object
 52  황화수소 평균(ppm)    0 non-null       float64
 53  황화수소 최소(ppm)    0 non-null       float64
 54  오존 최대(ppm)      0 non-null       float64
 55  오존 평균(ppm)      0 non-null       float64
 56  오존 최소(ppm)      0 non-null       float64
 57  등록일시            0 non-null       float64
dtypes: float64(57), object(1)
memory usage: 51.9+ MB
None

                                                                                                 모델번호  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1      25.6
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong        26.3
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong    24.7
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong  25.5
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong          24.8

                                                                                                  시리얼  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1      25.0
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong        26.2
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong    24.6
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong  25.0
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong          24.6

                                                                                                 측정시간  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1      24.3
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong        26.1
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong    24.4
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong  24.5
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong          24.4

                                                                                                   지역  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1       NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong         NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong     NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong  72.0
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong           NaN

                                                                                                  자치구  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1       NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong         NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong     NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong  70.0
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong           NaN

                                                                                                  행정동  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1       NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong         NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong     NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong  67.0
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong           NaN

                                                                                                 온도 최대(℃)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1           NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong             NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong         NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong       NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong               NaN

                                                                                                 온도 평균(℃)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1           NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong             NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong         NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong       NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong               NaN

                                                                                                 온도 최소(℃)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1           NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong             NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong         NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong       NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong               NaN

                                                                                                 습도 최대(%)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1           NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong             NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong         NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong       NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong               NaN

                                                                                                 ...  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1      ...
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong        ...
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong    ...
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong  ...
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong          ...

                                                                                                 암모니아 최대(ppm)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1               NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong                 NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong             NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong           NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong                   NaN

                                                                                                 암모니아 평균(ppm)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1               NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong                 NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong             NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong           NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong                   NaN

                                                                                                 암모니아 최소(ppm)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1               NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong                 NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong             NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong           NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong                   NaN

                                                                                                        황화수소 최대(ppm)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1      2026-06-22 00:07:17
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong        2026-06-22 00:07:17
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong    2026-06-22 00:07:17
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong  2026-06-22 00:07:17
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong          2026-06-22 00:07:17

                                                                                                 황화수소 평균(ppm)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1               NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong                 NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong             NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong           NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong                   NaN

                                                                                                 황화수소 최소(ppm)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1               NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong                 NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong             NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong           NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong                   NaN

                                                                                                 오존 최대(ppm)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1             NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong               NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong           NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong         NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong                 NaN

                                                                                                 오존 평균(ppm)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1             NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong               NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong           NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong         NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong                 NaN

                                                                                                 오존 최소(ppm)  \
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1             NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong               NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong           NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong         NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong                 NaN

                                                                                                 등록일시
SDOT001 OC3CL200011 2026-06-22_00:07:00 parks               Seoul_Grand_Park valet_parking1       NaN
        OC3CL200012 2026-06-22_00:07:00 traditional_markets Gwangjin-gu      Hwayang-dong         NaN
        OC3CL200019 2026-06-22_00:07:00 main_street         Yongsan-gu       Itaewon2(i)-dong     NaN
        OC3CL200017 2026-06-22_00:07:00 main_street         Gangdong-gu      Seongnae1(il)-dong   NaN
        OC3CL200015 2026-06-22_00:07:00 roads_and_parks     Gangnam-gu       Sinsa-dong           NaN

[5 rows x 58 columns]

In [3]:
cols = [
    "모델번호",
    "시리얼",
    "측정시간",
    "지역",
    "자치구",
    "행정동"
]

df = pd.read_csv(
    "../data/S-DoT_NATURE_2026.06.22-06.28.csv",
    encoding="cp949",
    index_col=False
)

df = df.rename(columns=dict(zip(df.columns[:6], cols)))
df.head()

/var/folders/c6/_5q2k4291yj3lw8b4k_0fc8m0000gn/T/ipykernel_88660/1148094641.py:10: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(

,모델번호,시리얼,측정시간,지역,자치구,행정동,온도 최대(℃),온도 평균(℃),온도 최소(℃),습도 최대(%),...,암모니아 최대(ppm),암모니아 평균(ppm),암모니아 최소(ppm),황화수소 최대(ppm),황화수소 평균(ppm),황화수소 최소(ppm),오존 최대(ppm),오존 평균(ppm),오존 최소(ppm),등록일시
0,SDOT001,OC3CL200011,2026-06-22_00:07:00,parks,Seoul_Grand_Park,valet_parking1,25.6,25.0,24.3,NaN,...,0.0,0.0,0.0,0.059,0.054,0.051,NaN,NaN,NaN,2026-06-22 00:07:17
1,SDOT001,OC3CL200012,2026-06-22_00:07:00,traditional_markets,Gwangjin-gu,Hwayang-dong,26.3,26.2,26.1,NaN,...,0.0,0.0,0.0,0.000,0.000,0.000,NaN,NaN,NaN,2026-06-22 00:07:17
2,SDOT001,OC3CL200019,2026-06-22_00:07:00,main_street,Yongsan-gu,Itaewon2(i)-dong,24.7,24.6,24.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-22 00:07:17
3,SDOT001,OC3CL200017,2026-06-22_00:07:00,main_street,Gangdong-gu,Seongnae1(il)-dong,25.5,25.0,24.5,72.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-22 00:07:17
4,SDOT001,OC3CL200015,2026-06-22_00:07:00,roads_and_parks,Gangnam-gu,Sinsa-dong,24.8,24.6,24.4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-22 00:07:17

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115114 entries, 0 to 115113
Data columns (total 58 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   모델번호            115114 non-null  object
 1   시리얼             115114 non-null  object
 2   측정시간            115114 non-null  object
 3   지역              115114 non-null  object
 4   자치구             115114 non-null  object
 5   행정동             115114 non-null  object
 6   온도 최대(℃)        106490 non-null  float64
 7   온도 평균(℃)        106490 non-null  float64
 8   온도 최소(℃)        106489 non-null  float64
 9   습도 최대(%)        91704 non-null   float64
 10  습도 평균(%)        92644 non-null   float64
 11  습도 최소(%)        93446 non-null   float64
 12  풍속 최대(m/s)      5639 non-null    float64
 13  풍속 평균(m/s)      5639 non-null    float64
 14  풍속 최소(m/s)      5639 non-null    float64
 15  풍향 최대(m/s)      5639 non-null    float64
 16  풍향 평균(m/s)      5639 non-null    float64
 17  풍향 최소(m/s)      5639 non-null    float64
 18  조도 최대(lux)      91069 non-null   float64
 19  조도 평균(lux)      91069 non-null   float64
 20  조도 최소(lux)      91069 non-null   float64
 21  자외선 최대(UV)      91885 non-null   float64
 22  자외선 평균(UV)      91885 non-null   float64
 23  자외선 최소(UV)      91885 non-null   float64
 24  소음 최대(dB)       108164 non-null  float64
 25  소음 평균(dB)       108164 non-null  float64
 26  소음 최소(dB)       108164 non-null  float64
 27  진동(x) 최대(mm/s)  86740 non-null   float64
 28  진동(x) 평균(mm/s)  86740 non-null   float64
 29  진동(x) 최소(mm/s)  86740 non-null   float64
 30  진동(y) 최대(mm/s)  86740 non-null   float64
 31  진동(y) 평균(mm/s)  86740 non-null   float64
 32  진동(y) 최소(mm/s)  86740 non-null   float64
 33  진동(z) 최대(mm/s)  86740 non-null   float64
 34  진동(z) 평균(mm/s)  86740 non-null   float64
 35  진동(z) 최소(mm/s)  86740 non-null   float64
 36  흑구온도 최대(℃)      3679 non-null    float64
 37  흑구온도 평균(℃)      3679 non-null    float64
 38  흑구온도 최소(℃)      3679 non-null    float64
 39  이산화질소 최대(ppm)   7943 non-null    float64
 40  이산화질소 평균(ppm)   7943 non-null    float64
 41  이산화질소 최소(ppm)   7943 non-null    float64
 42  일산화탄소 최대(ppm)   7943 non-null    float64
 43  일산화탄소 평균(ppm)   7943 non-null    float64
 44  일산화탄소 최소(ppm)   7943 non-null    float64
 45  이산화황 최대(ppm)    4505 non-null    float64
 46  이산화황 평균(ppm)    4558 non-null    float64
 47  이산화황 최소(ppm)    4558 non-null    float64
 48  암모니아 최대(ppm)    4525 non-null    float64
 49  암모니아 평균(ppm)    4525 non-null    float64
 50  암모니아 최소(ppm)    4525 non-null    float64
 51  황화수소 최대(ppm)    4525 non-null    float64
 52  황화수소 평균(ppm)    4525 non-null    float64
 53  황화수소 최소(ppm)    4525 non-null    float64
 54  오존 최대(ppm)      2934 non-null    float64
 55  오존 평균(ppm)      2934 non-null    float64
 56  오존 최소(ppm)      2934 non-null    float64
 57  등록일시            115114 non-null  object
dtypes: float64(51), object(7)
memory usage: 50.9+ MB

In [16]:
print(f"컬럼 명: {df.columns.tolist()}")

컬럼 명: ['모델번호', '시리얼', '측정시간', '지역', '자치구', '행정동', '온도 최대(℃)', '온도 평균(℃)', '온도 최소(℃)', '습도 최대(%)', '습도 평균(%)', '습도 최소(%)', '풍속 최대(m/s)', '풍속 평균(m/s)', '풍속 최소(m/s)', '풍향 최대(m/s)', '풍향 평균(m/s)', '풍향 최소(m/s)', '조도 최대(lux)', '조도 평균(lux)', '조도 최소(lux)', '자외선 최대(UV)', '자외선 평균(UV)', '자외선 최소(UV)', '소음 최대(dB)', '소음 평균(dB)', '소음 최소(dB)', '진동(x) 최대(mm/s)', '진동(x) 평균(mm/s)', '진동(x) 최소(mm/s)', '진동(y) 최대(mm/s)', '진동(y) 평균(mm/s)', '진동(y) 최소(mm/s)', '진동(z) 최대(mm/s)', '진동(z) 평균(mm/s)', '진동(z) 최소(mm/s)', '흑구온도 최대(℃)', '흑구온도 평균(℃)', '흑구온도 최소(℃)', '이산화질소 최대(ppm)', '이산화질소 평균(ppm)', '이산화질소 최소(ppm)', '일산화탄소 최대(ppm)', '일산화탄소 평균(ppm)', '일산화탄소 최소(ppm)', '이산화황 최대(ppm)', '이산화황 평균(ppm)', '이산화황 최소(ppm)', '암모니아 최대(ppm)', '암모니아 평균(ppm)', '암모니아 최소(ppm)', '황화수소 최대(ppm)', '황화수소 평균(ppm)', '황화수소 최소(ppm)', '오존 최대(ppm)', '오존 평균(ppm)', '오존 최소(ppm)', '등록일시']

### 센서 개수

In [9]:
print(f"센서 개수: {df['시리얼'].nunique()}")

센서 개수: 1002

### 자치구

In [12]:
print(f"자치구 개수: {df['자치구'].nunique()}")
print(f"자치구 이름: {df['자치구'].unique()}")

자치구 개수: 26
자치구 이름: ['Seoul_Grand_Park' 'Gwangjin-gu' 'Yongsan-gu' 'Gangdong-gu' 'Gangnam-gu'
 'Seongdong-gu' 'Gangseo-gu' 'Dobong-gu' 'Gwanak-gu' 'Jung-gu' 'Jongno-gu'
 'Eunpyeong-gu' 'Seodaemun-gu' 'Yangcheon-gu' 'Songpa-gu' 'Seocho-gu'
 'Geumcheon-gu' 'Gangbuk-gu' 'Dongjak-gu' 'Mapo-gu' 'Guro-gu' 'Nowon-gu'
 'Jungnang-gu' 'Yeongdeungpo-gu' 'Dongdaemun-gu' 'Seongbuk-gu']

### 행정동

In [13]:
print(f"행정동 개수: {df['행정동'].nunique()}")
print(f"행정동 이름: {df['행정동'].unique()}")

행정동 개수: 406
행정동 이름: ['valet_parking1' 'Hwayang-dong' 'Itaewon2(i)-dong' 'Seongnae1(il)-dong'
 'Sinsa-dong' 'Seongsu1ga2(i)-dong' 'Apgujeong-dong' 'Banghwa1(il)-dong'
 'Gonghang-dong' 'Yeoksam1(il)-dong' 'Guui1(il)-dong' 'Chang1(il)-dong'
 'Nakseongdae-dong' 'Myeong-dong' 'Seongsu1ga1(il)-dong'
 'Daechi4(sa)-dong' 'Samcheong-dong' 'Gayang1(il)-dong' 'Nokbeon-dong'
 'Hongje3(sam)-dong' 'Sinjeong4(sa)-dong' 'Jamsil6(yuk)-dong' 'Gahoe-dong'
 'Daejo-dong' 'Sogong-dong' 'Ihwa-dong' 'Chang4(sa)-dong'
 'Ssangmun3(sam)-dong' 'Gwanghui-dong' 'Banghwa3(sam)-dong' 'Sindang-dong'
 'Hoehyeon-dong' 'Dongseon-dong' 'Chang5-dong' 'Banghak1(il)-dong'
 'Bangbae2(i)-dong' 'Gasan-dong' 'Banpo1(il)-dong' 'Mok5(o)-dong'
 'Sinwol3(sam)-dong' 'Dunchon1(il)-dong' 'Songcheon-dong' 'SeoulGrandPark'
 'Cheonho2(i)-dong' 'Heukseok-dong' 'Mok2(i)-dong' 'Banpo4(sa)-dong'
 'Bulgwang2(i)-dong' 'Sang-do4(sa)-dong' 'Godeok2(i)-dong'
 'Seocho3(sam)-dong' 'Banpo3(sam)-dong' 'Yangjae1(il)-dong'
 'Seocho4(sa)-dong' 'Ssangmun4(sa)-dong' 'Banghwa2(i)-dong'
 'Dunchon2(i)-dong' 'Balsan1(il)-dong' 'Gil-dong' 'Amsa3(sam)-dong'
 'Hongeun2(i)-dong' 'Ssangmun1(il)-dong' 'Cheonho3(sam)-dong'
 'Cheonho1(il)-dong' 'Mangwon1(il)-dong' 'Beon3(sam)-dong'
 'Seongnae2(i)-dong' 'Suyu3(sam)-dong' 'Sadang1(il)-dong'
 'Sindaebang1(il)-dong' 'Sang-do3(sam)-dong' 'Seongnae3(sam)-dong'
 'Amsa1(il)-dong' 'Chang2(i)-dong' 'Sinjeong3(sam)-dong' 'Sinwol5(o)-dong'
 'Ssangmun2(i)-dong' 'Samyang-dong' 'Changsin1(il)-dong'
 'Dobong1(il)-dong' 'Godeok1(il)-dong' 'Insu-dong' 'Daechi2(i)-dong'
 'Sinjeong6(yuk)-dong' 'Hongeun1(il)-dong' 'Ilwonbon-dong' 'Suseo-dong'
 'Junggok3(sam)-dong' 'Hongje1(il)-dong' 'Chang3(sam)-dong'
 'Pyeongchang-dong' 'Eungam3(sam)-dong' 'Junggok4(sa)-dong'
 'Bukgajwa1(il)-dong' 'Sinjeong1(il)-dong' 'Nonhyeon1(il)-dong'
 'Ilwon1(il)-dong' 'Oryu2(i)-dong' 'Deungchon1(il)-dong'
 'Sanggye6(yuk).7(chil)-d' 'Bangbae3(sam)-dong' 'Jangji-dong'
 'Yongdap-dong' 'Hwagok8(pal)-dong' 'Eungam1(il)-dong' 'Sinnae1(il)-dong'
 'Dorim-dong' 'Gaepo4(sa)-dong' 'Jowon-dong' 'Segok-dong'
 'Gayang2(i)-dong' 'Yeomchang-dong' 'Deungchon2(i)-dong' 'Sugung-dong'
 'Sinwon-dong' 'Gwangjang-dong' 'Sajik-dong' 'Imun2(i)-dong'
 'Gu-ro3(sam)-dong' 'Cheongnyangni-dong' 'Jeongneung3(sam)-dong'
 'Wolgok2(i)-dong' 'Jong-ro5(o).6(yuk)-ga-d' 'Junghwa2(i)-dong'
 'Gusan-dong' 'Mangubon-dong' 'Junggye1(il)-dong' 'Seongbuk-dong'
 'Jingwan-dong' 'Jong-ro1(il).2(i).3(sam' 'Hangang-ro-dong' 'Sageun-dong'
 'Songjeong-dong' 'Sanggye1(il)-dong' 'Seongsan2(i)-dong' 'Sangam-dong'
 'Garak2(i)-dong' 'Sogang-dong' 'Yangjae2(i)-dong' 'Cheonyeon-dong'
 'Yonggang-dong' 'Sinsu-dong' 'Ahyeon-dong' 'Banpobon-dong' 'Seogyo-dong'
 'Seongsan1(il)-dong' 'Majang-dong' 'Sang-do1(il)-dong'
 'CheongwoonHyoja-dong' 'Beon2(i)-dong' 'Dapsip-ri2(i)-dong'
 'Myeonmokbon-dong' 'Jeonnong1(il)-dong' 'Junggok2(i)-dong'
 'Sangbong1(il)-dong' 'Mia-dong' 'Sinsa1(il)-dong' 'Gunja-dong'
 'Eungam2(i)-dong' 'Myeon-gil1(il)-dong' 'Sangbong2(i)-dong'
 'Geumho-2.3(i)(sam)-dong' 'Geumho4(sa)-dong' 'Gyonam-dong' 'Muak-dong'
 'Sangil-dong' 'Gaebong3(sam)-dong' 'Gangil-dong' 'Yongshin-dong'
 'Gu-ro1(il)-dong' 'Gaebong2(i)-dong' 'Gaebong1(il)-dong' 'Gu-ro2(i)-dong'
 'Gu-ro5(o)-dong' 'Hwagok1(il)-dong' 'Gocheok2(i)-dong' 'Hang-dong'
 'Ujangsan-dong' 'Hwagok6(yuk)-dong' 'Dapsip-ri1(il)-dong'
 'Gocheok1(il)-dong' 'Jeonnong2(i)-dong' 'Hoegi-dong' 'Daerim3(sam)-dong'
 'Gaepo2(i)-dong' 'Samseong2(i)-dong' 'Jangwi2(i)-dong'
 'Samseong1(il)-dong' 'Jangwi3(sam)-dong' 'Naegok-dong'
 'Gongneung1(il)-dong' 'Bangbae4(sa)-dong' 'Jangan1(il)-dong'
 'Sanggye8(pal)-dong' 'Dangsan1(il)-dong' 'Hwigyeong2(i)-dong'
 'Hwigyeong1(il)-dong' 'Yeouido-dong' 'Sindorim-dong' 'Daerim1(il)-dong'
 'Jangan2(i)-dong' 'Sanggye3(sam).4(sa)-don' 'Daerim2(i)-dong'
 'Daechi1(il)-dong' 'Hagye1(il)-dong' 'Gayang3(sam)-dong'
 'Gu-ro4(sa)-dong' 'Dogok2(i)-dong' 'Bangbae1(il)-dong' 'Sanggye5(o)-dong'
 'Seokgwan-dong' 'Hagye2(i)-dong' 'Wolgye2(i)-dong' 'Yangpyeong2(i)-dong'
 'Ui-dong' 'Oryu1(il)-dong' 'Hwagok4(sa)-dong' 'Myeonmok4(sa)-dong'
 'Dangsan2(i)-dong' 'Hwagokbon-dong' 'Cheongdam-dong' 'Hwagok2(i)-dong'
 'Sin-gil4(sa)-dong' 'Sin-gil7(chil)-dong' 'Junggyebon-dong'
 'Sadang2(i)-dong' 'Sin-gil1(il)-dong' 'Yeongdeungpo-dong'
 'Sin-gil6(yuk)-dong' 'Banghak2(i)-dong' 'Jamsilbon-dong'
 'Junggok1(il)-dong' 'Sinchon-dong' 'Wolgok1(il)-dong' 'Samgaksan-dong'
 'Junggye4(sa)-dong' 'Gongneung2(i)-dong' 'Muk2(i)-dong' 'Munllae-dong'
 'Siheung2(i)-dong' 'Wolgye1(il)-dong' 'Dogok1(il)-dong'
 'Sanggye9(gu)-dong' 'Muk1(il)-dong' 'Sinwol1(il)-dong' 'Ilwon2(i)-dong'
 'Doksan4(sa)-dong' 'Yangpyeong1(il)-dong' 'Sinnae2(i)-dong'
 'Myeonmok3(sam).8(pal)-d' 'Wangsimni2(i)-dong' 'Dobong2(i)-dong'
 'Samseong-dong' 'Nonhyeon2(i)-dong' 'Man-gu3(sam)-dong' 'Bomun-dong'
 'Noryangjin1(il)-dong' 'Anam-dong' 'Sanggye10(sip)-dong'
 'Wolgye3(sam)-dong' 'Samseon-dong' 'Sadang3(sam)-dong' 'Guui2(i)-dong'
 'Daebang-dong' 'Neung-dong' 'Yeoksam2(i)-dong' 'Junghwa1(il)-dong'
 'Gaepo1(il)-dong' 'Noryangjin2(i)-dong' 'Sang-do2(i)-dong'
 'Donam1(il)-dong' 'Banghak3(sam)-dong' 'Galhyeon2(i)-dong'
 'Gileum2(i)-dong' 'Jeungsan-dong' 'Myeon-gil2(i)-dong' 'Gileum1(il)-dong'
 'Donam2(i)-dong' 'Amsa2(i)-dong' 'Sindaebang2(i)-dong' 'Suyu1(il)-dong'
 'Jangwi1(il)-dong' 'Jeongneung1(il)-dong' 'Jayang4(sa)-dong'
 'Jeongneung2(i)-dong' 'Sadang4(sa)-dong' 'Jayang2(i)-dong'
 'Guui3(sam)-dong' 'Jayang3(sam)-dong' 'Seocho1(il)-dong'
 'Jeongneung4(sa)-dong' 'Sadang5(o)-dong' 'Seocho2(i)-dong'
 'Jayang1(il)-dong' 'Doksan1(il)-dong' 'Sinjeong7(chil)-dong'
 'Beon1(il)-dong' 'Susaek-dong' 'Haengun-dong' 'Daehak-dong'
 'Sinllim-dong' 'Sinjeong2(i)-dong' 'Boramae-dong' 'Mangwon2(i)-dong'
 'Sinwol7(chil)-dong' 'Yeonnam-dong' 'Bukgajwa2(i)-dong' 'Yeonhui-dong'
 'Geumho-1(il)-dong' 'Doksan2(i)-dong' 'Sinwol6(yuk)-dong'
 'Bukahyeon-dong' 'Mok4(sa)-dong' 'Pil-dong' 'Cheongnyong-dong'
 'Eungbong-dong' 'Seongsu2ga1(il)-dong' 'Dohwa-dong' 'Haengdang2(i)-dong'
 'Jungnim-dong' 'Seonghyeon-dong' 'Seorim-dong' 'Chunghyeon-dong'
 'Namgajwa2(i)-dong' 'Jamwon-dong' 'Jeonnong3(sam)-dong' 'Hyochang-dong'
 'Cheongpa-dong' 'Hwanghak-dong' 'Nangok-dong' 'Yeomni-dong'
 'Donghwa-dong' 'Daeheung-dong' 'Sindang5(o)-dong' 'Jungang-dong'
 'Miseong-dong' 'Itaewon1(il)-dong' 'Eulji-ro-dong' 'Wangsimni-doSeondong'
 'Jangchung-dong' 'Namgajwa1(il)-dong' 'Wonhyo-ro-1(il)-dong' 'Dasan-dong'
 'Bogwang-dong' 'Huam-dong' 'Seongsu2ga3(sam)-dong' 'Wonhyo-ro-2(i)-dong'
 'Cheonggu-dong' 'Yaksu-dong' 'Ichon2(i)-dong' 'Hapjeong-dong' 'Oksu-dong'
 'Gongdeok-dong' 'Cheongnim-dong' 'Siheung5(o)-dong' 'Haengdang1(il)-dong'
 'Yongsan2(i)-dong' 'Namhyeon-dong' 'Ichon1(il)-dong' 'Inheon-dong'
 'Sungin1(il)-dong' 'Nanhyang-dong' 'Garakbon-dong' 'Siheung3(sam)-dong'
 'Siheung1(il)-dong' 'Euncheon-dong' 'Hannam-dong' 'Songpa2(i)-dong'
 'Sinwol2(i)-dong' 'Jamsil2(i)-dong' 'Bangi2(i)-dong' 'Hyehwa-dong'
 'Changsin2(i)-dong' 'Yongmun-dong' 'Seobinggo-dong' 'Ogeum-dong'
 'Geoyeo1(il)-dong' 'Sinwol4(sa)-dong' 'Mok3(sam)-dong' 'Oryun-dong'
 'Seokchon-dong' 'Samjeon-dong' 'Songpa1(il)-dong' 'Siheung4(sa)-dong'
 'Mok1(il)-dong' 'Wirye-dong' 'Geoyeo2(i)-dong' 'Hwagok3(sam)-dong'
 'Jamsil3(sam)-dong' 'Macheon2(i)-dong' 'Buam-dong' 'Jamsil4(sa)-dong'
 'Sungin2(i)-dong' 'Pungnap2(i)-dong' 'Banpo2(i)-dong'
 'Munjeong1(il)-dong' 'Pungnap1(il)-dong' 'Bangi1(il)-dong'
 'Munjeong2(i)-dong' 'Bulgwang1(il)-dong' 'Sanggye2(i)-dong'
 'Garibong-dong' 'meeting_bridge2' 'Jongam-dong' 'Galhyeon1(il)-dong'
 'Suyu2(i)-dong']

### 지역

In [14]:
print(f"지역 개수: {df['지역'].nunique()}")
print(f"지역 이름: {df['지역'].unique()}")

지역 개수: 8
지역 이름: ['parks' 'traditional_markets' 'main_street' 'roads_and_parks'
 'industrial_area' 'residential_area' 'commercial_area'
 'public_facilities']

### 결측치

In [17]:
missing = df.isnull().sum().sort_values(ascending=False)
missing_ratio = (missing / len(df) * 100).round(2)

pd.DataFrame({
    "missing": missing,
    "ratio(%)": missing_ratio
})

                missing  ratio(%)
오존 최소(ppm)       112180     97.45
오존 평균(ppm)       112180     97.45
오존 최대(ppm)       112180     97.45
흑구온도 최대(℃)       111435     96.80
흑구온도 평균(℃)       111435     96.80
흑구온도 최소(℃)       111435     96.80
이산화황 최대(ppm)     110609     96.09
암모니아 최소(ppm)     110589     96.07
황화수소 최소(ppm)     110589     96.07
암모니아 평균(ppm)     110589     96.07
암모니아 최대(ppm)     110589     96.07
황화수소 평균(ppm)     110589     96.07
황화수소 최대(ppm)     110589     96.07
이산화황 최소(ppm)     110556     96.04
이산화황 평균(ppm)     110556     96.04
풍향 최소(m/s)       109475     95.10
풍향 최대(m/s)       109475     95.10
풍향 평균(m/s)       109475     95.10
풍속 최소(m/s)       109475     95.10
풍속 평균(m/s)       109475     95.10
풍속 최대(m/s)       109475     95.10
일산화탄소 평균(ppm)    107171     93.10
일산화탄소 최대(ppm)    107171     93.10
이산화질소 최소(ppm)    107171     93.10
이산화질소 평균(ppm)    107171     93.10
이산화질소 최대(ppm)    107171     93.10
일산화탄소 최소(ppm)    107171     93.10
진동(y) 최소(mm/s)    28374     24.65
진동(z) 최소(mm/s)    28374     24.65
진동(z) 평균(mm/s)    28374     24.65
진동(z) 최대(mm/s)    28374     24.65
진동(x) 최소(mm/s)    28374     24.65
진동(y) 평균(mm/s)    28374     24.65
진동(y) 최대(mm/s)    28374     24.65
진동(x) 평균(mm/s)    28374     24.65
진동(x) 최대(mm/s)    28374     24.65
조도 최대(lux)        24045     20.89
조도 평균(lux)        24045     20.89
조도 최소(lux)        24045     20.89
습도 최대(%)          23410     20.34
자외선 평균(UV)        23229     20.18
자외선 최대(UV)        23229     20.18
자외선 최소(UV)        23229     20.18
습도 평균(%)          22470     19.52
습도 최소(%)          21668     18.82
온도 최소(℃)           8625      7.49
온도 평균(℃)           8624      7.49
온도 최대(℃)           8624      7.49
소음 최대(dB)          6950      6.04
소음 최소(dB)          6950      6.04
소음 평균(dB)          6950      6.04
모델번호                  0      0.00
시리얼                   0      0.00
행정동                   0      0.00
자치구                   0      0.00
지역                    0      0.00
측정시간                  0      0.00
등록일시                  0      0.00

In [18]:
df.dtypes

모델번호               object
시리얼                object
측정시간               object
지역                 object
자치구                object
행정동                object
온도 최대(℃)          float64
온도 평균(℃)          float64
온도 최소(℃)          float64
습도 최대(%)          float64
습도 평균(%)          float64
습도 최소(%)          float64
풍속 최대(m/s)        float64
풍속 평균(m/s)        float64
풍속 최소(m/s)        float64
풍향 최대(m/s)        float64
풍향 평균(m/s)        float64
풍향 최소(m/s)        float64
조도 최대(lux)        float64
조도 평균(lux)        float64
조도 최소(lux)        float64
자외선 최대(UV)        float64
자외선 평균(UV)        float64
자외선 최소(UV)        float64
소음 최대(dB)         float64
소음 평균(dB)         float64
소음 최소(dB)         float64
진동(x) 최대(mm/s)    float64
진동(x) 평균(mm/s)    float64
진동(x) 최소(mm/s)    float64
진동(y) 최대(mm/s)    float64
진동(y) 평균(mm/s)    float64
진동(y) 최소(mm/s)    float64
진동(z) 최대(mm/s)    float64
진동(z) 평균(mm/s)    float64
진동(z) 최소(mm/s)    float64
흑구온도 최대(℃)        float64
흑구온도 평균(℃)        float64
흑구온도 최소(℃)        float64
이산화질소 최대(ppm)     float64
이산화질소 평균(ppm)     float64
이산화질소 최소(ppm)     float64
일산화탄소 최대(ppm)     float64
일산화탄소 평균(ppm)     float64
일산화탄소 최소(ppm)     float64
이산화황 최대(ppm)      float64
이산화황 평균(ppm)      float64
이산화황 최소(ppm)      float64
암모니아 최대(ppm)      float64
암모니아 평균(ppm)      float64
암모니아 최소(ppm)      float64
황화수소 최대(ppm)      float64
황화수소 평균(ppm)      float64
황화수소 최소(ppm)      float64
오존 최대(ppm)        float64
오존 평균(ppm)        float64
오존 최소(ppm)        float64
등록일시               object
dtype: object

### 센서별 데이터 개수

In [21]:
sensor_count = df.groupby("시리얼").size()

sensor_count.describe()

count    1002.000000
mean      114.884232
std        17.761281
min         1.000000
25%       120.000000
50%       120.000000
75%       120.000000
max       120.000000
dtype: float64

### 중복 데이터 확인

In [22]:
df.duplicated().sum()

0

In [23]:
df.describe()

,온도 최대(℃),온도 평균(℃),온도 최소(℃),습도 최대(%),습도 평균(%),습도 최소(%),풍속 최대(m/s),풍속 평균(m/s),풍속 최소(m/s),풍향 최대(m/s),...,이산화황 최소(ppm),암모니아 최대(ppm),암모니아 평균(ppm),암모니아 최소(ppm),황화수소 최대(ppm),황화수소 평균(ppm),황화수소 최소(ppm),오존 최대(ppm),오존 평균(ppm),오존 최소(ppm)
count,106490.00000,106490.000000,106489.000000,91704.000000,92644.000000,93446.000000,5639.000000,5639.000000,5639.000000,5639.000000,...,4558.000000,4525.000000,4525.000000,4525.000000,4525.000000,4525.000000,4525.000000,2934.000000,2934.000000,2934.000000
mean,26.58637,26.089272,25.620539,65.066246,63.362700,61.568114,1.588544,1.023479,0.803157,266.711101,...,0.003355,0.003857,0.003218,0.002814,0.007967,0.006891,0.005975,0.351124,0.336922,0.328308
std,3.69986,3.544925,3.412780,10.959029,11.321266,11.684648,2.566891,2.488168,2.457457,109.116293,...,0.001345,0.097614,0.097181,0.096976,0.031472,0.028862,0.026290,0.682650,0.670806,0.670437
min,11.90000,2.000000,0.100000,25.000000,22.000000,7.000000,0.100000,0.100000,0.100000,0.200000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,24.00000,23.600000,23.300000,57.000000,55.000000,53.000000,0.200000,0.100000,0.100000,226.350000,...,0.003000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.037000,0.033000,0.028000
50%,25.90000,25.500000,25.100000,65.000000,63.000000,61.000000,1.000000,0.300000,0.100000,315.500000,...,0.004000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.060000,0.055000,0.050000
75%,29.20000,28.600000,28.000000,74.000000,72.000000,71.000000,1.600000,0.600000,0.200000,351.800000,...,0.004000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.095000,0.087000,0.079000
max,54.40000,41.400000,39.400000,89.000000,89.000000,89.000000,13.000000,10.900000,10.800000,359.900000,...,0.009000,6.495000,6.495000,6.495000,0.293000,0.282000,0.255000,2.000000,2.000000,2.000000

### 지역별 센서 개수

In [24]:
df["지역"].value_counts()

지역
residential_area       82161
roads_and_parks        13916
traditional_markets     4945
main_street             4425
industrial_area         4396
commercial_area         3698
parks                    943
public_facilities        630
Name: count, dtype: int64

### 자치구별 센서 개수

In [25]:
df.groupby("자치구")["시리얼"].nunique().sort_values()

자치구
Seoul_Grand_Park     4
Geumcheon-gu        18
Yongsan-gu          21
Jungnang-gu         22
Dongdaemun-gu       23
Seongbuk-gu         27
Yeongdeungpo-gu     27
Guro-gu             28
Seodaemun-gu        28
Gangbuk-gu          29
Gwangjin-gu         30
Eunpyeong-gu        31
Nowon-gu            31
Dongjak-gu          32
Jung-gu             35
Songpa-gu           38
Seocho-gu           40
Dobong-gu           42
Gangnam-gu          44
Gangseo-gu          47
Jongno-gu           57
Gwanak-gu           61
Seongdong-gu        62
Mapo-gu             72
Yangcheon-gu        74
Gangdong-gu         79
Name: 시리얼, dtype: int64

### 행정동별 센서 개수

In [26]:
df.groupby("행정동")["시리얼"].nunique().sort_values()

행정동
Jeonnong2(i)-dong        1
Jeongneung1(il)-dong     1
Jeongneung2(i)-dong      1
Jeongneung4(sa)-dong     1
meeting_bridge2          1
                        ..
Cheonho1(il)-dong        8
Mok5(o)-dong             9
Mangwon1(il)-dong        9
Amsa1(il)-dong          11
Cheonho2(i)-dong        12
Name: 시리얼, Length: 406, dtype: int64

In [37]:
sensor_feature = (
    df.groupby("시리얼")
      .agg({
          "풍속 평균(m/s)": lambda x: x.notna().any(),
          "오존 평균(ppm)": lambda x: x.notna().any(),
          "흑구온도 평균(℃)": lambda x: x.notna().any(),
          "온도 평균(℃)": lambda x: x.notna().any()
      })
)

sensor_feature.sum()

풍속 평균(m/s)     53
오존 평균(ppm)     27
흑구온도 평균(℃)     32
온도 평균(℃)      938
dtype: int64