# Export Parquet
- S-DoT 병합 데이터에 위경도 정보 매핑 후 parquet으로 저장

터미널에 다음 명령어 실행  
`pip install duckdb polars pyarrow jupyter`

In [1]:
import duckdb
import polars as pl
import os

# 1. 파일 경로 설정 (notebooks 폴더 안에서 실행하므로 상위 폴더로 이동 필요)
BASE_DIR = os.path.abspath('..')
DATA_PATH = os.path.join(BASE_DIR, 'data', 'processed', 'sdot_master_2020_2026.csv')

# 경로가 올바른지 확인
print(f"데이터 경로: {DATA_PATH}")
print(f"파일 존재 여부: {os.path.exists(DATA_PATH)}")

# 2. DuckDB와 Polars의 호환성을 높여주는 PyArrow 활성화
pl.Config.set_tbl_rows(10) # 출력 시 보여줄 행 개수 설정

데이터 경로: /Users/gomdori/Documents/Git/sdot-analysis/data/processed/sdot_master_2020_2026.csv
파일 존재 여부: True

polars.config.Config

# 전체 행 개수 확인
- 34,014,535행

In [2]:
# 1. 전체 데이터 행 개수 확인 
query_count = f"""
    SELECT COUNT(*) AS total_rows 
    FROM '{DATA_PATH}'
"""
print("📌 [데이터 총 행 개수]")
display(duckdb.sql(query_count).pl())

# 2. 상위 5개 행 엿보기 
query_head = f"""
    SELECT * 
    FROM '{DATA_PATH}' 
    LIMIT 5
"""
print("\n📌 [상위 5개 행 데이터 미리보기]")
display(duckdb.sql(query_head).pl())

📌 [데이터 총 행 개수]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

shape: (1, 1)
┌────────────┐
│ total_rows │
│ ---        │
│ i64        │
╞════════════╡
│ 34014535   │
└────────────┘

📌 [상위 5개 행 데이터 미리보기]

shape: (5, 128)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ measure_ti ┆ sensor_id ┆ temp_max ┆ temp_avg ┆ … ┆ flag_o3_a ┆ flag_o3_m ┆ flag_pm10 ┆ flag_pm25 │
│ me         ┆ ---       ┆ ---      ┆ ---      ┆   ┆ vg        ┆ in        ┆ ---       ┆ ---       │
│ ---        ┆ str       ┆ str      ┆ f64      ┆   ┆ ---       ┆ ---       ┆ i64       ┆ i64       │
│ str        ┆           ┆          ┆          ┆   ┆ i64       ┆ i64       ┆           ┆           │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2020.4.1   ┆ V02Q19400 ┆ null     ┆ 14.0     ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1         │
│ 1:00       ┆ 43        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2020.4.1   ┆ V02Q19400 ┆ null     ┆ 16.6     ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1         │
│ 12:00      ┆ 43        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2020.4.1   ┆ V02Q19400 ┆ null     ┆ 15.0     ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1         │
│ 18:00      ┆ 43        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2020.4.2   ┆ V02Q19400 ┆ null     ┆ 9.0      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1         │
│ 0:00       ┆ 43        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2020.4.2   ┆ V02Q19400 ┆ null     ┆ 7.7      ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ 1         │
│ 6:00       ┆ 43        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

# measure_time 포맷 지정

In [3]:
query_find_new_format = f"""
    SELECT measure_time, COUNT(*) as count
    FROM '{DATA_PATH}'
    WHERE TRY_CAST(REPLACE(measure_time, '.', '-') AS TIMESTAMP) IS NULL
      AND length(measure_time) > 10  -- 쓰레기 이상치 데이터 제외
    GROUP BY measure_time
    ORDER BY count DESC
    LIMIT 10
"""

print("📌 [변환 실패한 날짜 포맷 정체 확인]")
display(duckdb.sql(query_find_new_format).pl())

📌 [변환 실패한 날짜 포맷 정체 확인]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

shape: (10, 2)
┌─────────────────────┬────────┐
│ measure_time        ┆ count  │
│ ---                 ┆ ---    │
│ str                 ┆ i64    │
╞═════════════════════╪════════╡
│ 202000000000.0      ┆ 355782 │
│ 2022-12-31_12:07:00 ┆ 8396   │
│ 2022-12-31_01:07:00 ┆ 8396   │
│ 2022-12-30_08:07:00 ┆ 8392   │
│ 2022-12-30_09:07:00 ┆ 8392   │
│ 2022-12-30_11:07:00 ┆ 8392   │
│ 2022-12-31_06:07:00 ┆ 8392   │
│ 2022-12-31_08:07:00 ┆ 8392   │
│ 2022-12-30_06:07:00 ┆ 8392   │
│ 2022-12-31_05:07:00 ┆ 8392   │
└─────────────────────┴────────┘

In [4]:
query_final_time_range = f"""
    SELECT 
        MIN(TRY_CAST(REPLACE(REPLACE(measure_time, '.', '-'), '_', ' ') AS TIMESTAMP)) AS start_time,
        MAX(TRY_CAST(REPLACE(REPLACE(measure_time, '.', '-'), '_', ' ') AS TIMESTAMP)) AS end_time
    FROM '{DATA_PATH}'
"""

print("📌 [최종 데이터 측정 시간 범위]")
display(duckdb.sql(query_final_time_range).pl())

📌 [최종 데이터 측정 시간 범위]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

shape: (1, 2)
┌─────────────────────┬─────────────────────┐
│ start_time          ┆ end_time            │
│ ---                 ┆ ---                 │
│ datetime[μs]        ┆ datetime[μs]        │
╞═════════════════════╪═════════════════════╡
│ 2020-04-01 01:00:00 ┆ 2026-07-19 23:07:00 │
└─────────────────────┴─────────────────────┘

# view 생성
- 시계열 분석을 할 때마다 매 쿼리에 TRY_CAST와 REPLACE 로직을 길게 쓰면 쿼리 속도에 영향
- 날짜를 TIMESTAMP 타입으로 변환한 파생 컬럼을 추가한 뷰 생성

In [5]:
# 1. 뷰(View) 생성 쿼리
query_create_view = f"""
    CREATE OR REPLACE VIEW v_sdot_clean AS
    SELECT 
        *,
        TRY_CAST(REPLACE(REPLACE(measure_time, '.', '-'), '_', ' ') AS TIMESTAMP) AS measure_timestamp
    FROM '{DATA_PATH}'
    WHERE TRY_CAST(REPLACE(REPLACE(measure_time, '.', '-'), '_', ' ') AS TIMESTAMP) IS NOT NULL
"""

# 뷰 생성 실행
duckdb.sql(query_create_view)
print("✅ 깔끔한 시계열 분석을 위한 뷰(v_sdot_clean) 생성 완료!\n")

# 2. 뷰가 잘 만들어졌는지 상위 5개 확인
query_check_view = """
    SELECT 
        measure_time AS "원본_문자열(str)", 
        measure_timestamp AS "변환된_날짜(timestamp)"
    FROM v_sdot_clean
    LIMIT 5
"""

print("📌 [뷰 데이터 미리보기]")
display(duckdb.sql(query_check_view).pl())

✅ 깔끔한 시계열 분석을 위한 뷰(v_sdot_clean) 생성 완료!

📌 [뷰 데이터 미리보기]

shape: (5, 2)
┌──────────────────┬────────────────────────┐
│ 원본_문자열(str) ┆ 변환된_날짜(timestamp) │
│ ---              ┆ ---                    │
│ str              ┆ datetime[μs]           │
╞══════════════════╪════════════════════════╡
│ 2020.4.1 1:00    ┆ 2020-04-01 01:00:00    │
│ 2020.4.1 12:00   ┆ 2020-04-01 12:00:00    │
│ 2020.4.1 18:00   ┆ 2020-04-01 18:00:00    │
│ 2020.4.2 0:00    ┆ 2020-04-02 00:00:00    │
│ 2020.4.2 6:00    ┆ 2020-04-02 06:00:00    │
└──────────────────┴────────────────────────┘

# [0] 위경도 정보 매핑 (view 업데이트)

In [6]:
import pandas as pd
import duckdb

# 1. 엑셀 파일 로드 및 컬럼명 변경
loc_df = pd.read_excel('../metadata/서울시 도시데이터 센서(S-DoT) 환경정보 설치 위치정보.xlsx') #[cite: 1]
loc_df = loc_df.rename(columns={'모델 시리얼(*)': '시리얼'}) #[cite: 1]

# 2. 변경 전 시리얼 매핑 테이블 구축[cite: 1]
old_serial_map = {}
for _, row in loc_df.iterrows():
    if pd.notna(row['변경 전 시리얼']): #[cite: 1]
        old_serial_map[row['변경 전 시리얼']] = row['시리얼'] #[cite: 1]
    if pd.notna(row['변경 전 시리얼(데이터 상 표기)']): #[cite: 1]
        old_serial_map[row['변경 전 시리얼(데이터 상 표기)']] = row['시리얼'] #[cite: 1]

# DuckDB에 위치 데이터 프레임 등록
duckdb.register('loc_table', loc_df)

# 3. 매핑 로직을 반영한 최종 View 생성
# 원본 데이터의 sensor_id가 old_serial_map에 있으면 신규 시리얼로 변경 후 JOIN
query_create_final_view = """
    CREATE OR REPLACE VIEW v_sdot_final AS
    WITH mapped_data AS (
        SELECT 
            *,
            COALESCE(
                (SELECT 시리얼 FROM loc_table WHERE "변경 전 시리얼" = d.sensor_id OR "변경 전 시리얼(데이터 상 표기)" = d.sensor_id LIMIT 1), 
                sensor_id
            ) AS sensor_id_matched
        FROM v_sdot_clean d
    )
    SELECT 
        m.*,
        l.위도 AS lat,
        l.경도 AS lon,
        l.주소 AS address
    FROM mapped_data m
    LEFT JOIN loc_table l ON m.sensor_id_matched = l.시리얼
"""

# 뷰 생성 
duckdb.sql(query_create_final_view)
print("✅ 위경도 매핑이 완료된 최종 뷰(v_sdot_final) 생성 완료!")

# 생성된 뷰 SELECT 문으로 조회
query_check_final = "SELECT * FROM v_sdot_final LIMIT 5"
display(duckdb.sql(query_check_final).pl())

✅ 위경도 매핑이 완료된 최종 뷰(v_sdot_final) 생성 완료!

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

shape: (5, 133)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ measure_ti ┆ sensor_id ┆ temp_max ┆ temp_avg ┆ … ┆ sensor_id ┆ lat       ┆ lon       ┆ address   │
│ me         ┆ ---       ┆ ---      ┆ ---      ┆   ┆ _matched  ┆ ---       ┆ ---       ┆ ---       │
│ ---        ┆ str       ┆ str      ┆ f64      ┆   ┆ ---       ┆ f64       ┆ f64       ┆ str       │
│ str        ┆           ┆          ┆          ┆   ┆ str       ┆           ┆           ┆           │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2020.4.21  ┆ V02Q19401 ┆ null     ┆ 7.7      ┆ … ┆ V02Q19401 ┆ 37.507059 ┆ 126.90711 ┆ 서울특별  │
│ 21:00      ┆ 97        ┆          ┆          ┆   ┆ 97        ┆           ┆ 2         ┆ 시        │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 영등포구  │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 신길로39  │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 길 33     │
│ 2020.4.22  ┆ V02Q19401 ┆ null     ┆ 8.2      ┆ … ┆ V02Q19401 ┆ 37.507059 ┆ 126.90711 ┆ 서울특별  │
│ 3:00       ┆ 97        ┆          ┆          ┆   ┆ 97        ┆           ┆ 2         ┆ 시        │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 영등포구  │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 신길로39  │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 길 33     │
│ 2020.4.22  ┆ V02Q19401 ┆ null     ┆ 7.3      ┆ … ┆ V02Q19401 ┆ 37.507059 ┆ 126.90711 ┆ 서울특별  │
│ 9:00       ┆ 97        ┆          ┆          ┆   ┆ 97        ┆           ┆ 2         ┆ 시        │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 영등포구  │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 신길로39  │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 길 33     │
│ 2020.4.22  ┆ V02Q19401 ┆ null     ┆ 9.7      ┆ … ┆ V02Q19401 ┆ 37.507059 ┆ 126.90711 ┆ 서울특별  │
│ 15:00      ┆ 97        ┆          ┆          ┆   ┆ 97        ┆           ┆ 2         ┆ 시        │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 영등포구  │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 신길로39  │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 길 33     │
│ 2020.4.22  ┆ V02Q19401 ┆ null     ┆ 8.4      ┆ … ┆ V02Q19401 ┆ 37.507059 ┆ 126.90711 ┆ 서울특별  │
│ 21:00      ┆ 97        ┆          ┆          ┆   ┆ 97        ┆           ┆ 2         ┆ 시        │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 영등포구  │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 신길로39  │
│            ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆ 길 33     │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
# 1. 자치구별 고유 센서 분포 확인
query_district_check = """
    WITH sensor_districts AS (
        SELECT 
            sensor_id_matched,
            address,
            SPLIT_PART(address, ' ', 2) AS district
        FROM v_sdot_final
        GROUP BY sensor_id_matched, address
    )
    SELECT 
        district AS 자치구,
        COUNT(*) AS 센서_개수
    FROM sensor_districts
    GROUP BY district
    ORDER BY 센서_개수 DESC
"""

df_district_check = duckdb.sql(query_district_check).pl()
print("📌 [정상 매핑 확인: 자치구별 센서 개수]")
display(df_district_check)

print("-" * 50)

# 2. 매핑 이상치(결측치 또는 '구'로 끝나지 않는 주소) 추출
query_anomaly_check = """
    WITH sensor_districts AS (
        SELECT 
            sensor_id_matched,
            address,
            SPLIT_PART(address, ' ', 2) AS district
        FROM v_sdot_final
        GROUP BY sensor_id_matched, address
    )
    SELECT 
        sensor_id_matched,
        address,
        district AS 잘못_추출된_자치구
    FROM sensor_districts
    WHERE address IS NULL 
       OR district NOT LIKE '%구'
"""

df_anomaly = duckdb.sql(query_anomaly_check).pl()
print(f"🚨 [이상치 확인: 형식이 어긋나거나 누락된 데이터 총 {len(df_anomaly)}건]")
display(df_anomaly)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

📌 [정상 매핑 확인: 자치구별 센서 개수]

shape: (27, 2)
┌──────────┬───────────┐
│ 자치구   ┆ 센서_개수 │
│ ---      ┆ ---       │
│ str      ┆ i64       │
╞══════════╪═══════════╡
│ 마포구   ┆ 86        │
│ 양천구   ┆ 84        │
│ 강동구   ┆ 84        │
│ 성동구   ┆ 76        │
│ 관악구   ┆ 75        │
│ …        ┆ …         │
│ 동대문구 ┆ 29        │
│ 용산구   ┆ 27        │
│ 금천구   ┆ 24        │
│ null     ┆ 20        │
│          ┆ 5         │
└──────────┴───────────┘

--------------------------------------------------

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

🚨 [이상치 확인: 형식이 어긋나거나 누락된 데이터 총 25건]

shape: (25, 3)
┌───────────────────┬─────────────────────────────────┬────────────────────┐
│ sensor_id_matched ┆ address                         ┆ 잘못_추출된_자치구 │
│ ---               ┆ ---                             ┆ ---                │
│ str               ┆ str                             ┆ str                │
╞═══════════════════╪═════════════════════════════════╪════════════════════╡
│ OC3CL200805       ┆ null                            ┆ null               │
│ OC3CL200801       ┆ null                            ┆ null               │
│ OC3DL220002       ┆ null                            ┆ null               │
│ OT3CL180000       ┆ null                            ┆ null               │
│ V02Q1940963       ┆ null                            ┆ null               │
│ …                 ┆ …                               ┆ …                  │
│ OC3CL200065       ┆ 서울대공원                      ┆                    │
│ OC3CL200140       ┆ 서울특별시  강남구 일원동       ┆                    │
│                   ┆ 246-13                          ┆                    │
│ V02Q1950001       ┆ null                            ┆ null               │
│ OT2CL200002       ┆ null                            ┆ null               │
│ V02Q1940922       ┆ null                            ┆ null               │
└───────────────────┴─────────────────────────────────┴────────────────────┘

In [8]:
 import pandas as pd

# 텍스트가 긴 주소도 잘리지 않고 다 보이도록 설정
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 30)

print("📌 [이상치 25건 전체 데이터 확인]")
display(df_anomaly.to_pandas())

📌 [이상치 25건 전체 데이터 확인]

   sensor_id_matched                address 잘못_추출된_자치구
0        OC3CL200805                   None       None
1        OC3CL200801                   None       None
2        OC3DL220002                   None       None
3        OT3CL180000                   None       None
4        V02Q1940963                   None       None
5        V02Q1940921                   None       None
6        OC3CL200810                   None       None
7        OC3CL200807                   None       None
8        OC3CL200806                   None       None
9        V02Q1940933                   None       None
10       V02Q1940936                   None       None
11       OC3CL200061                  서울대공원
12       OC3CL200803                   None       None
13       OC3CL200804                   None       None
14       V02Q1940982                   None       None
15       OC3CL200010                  서울대공원
16       OC3CL200802                   None       None
17       OC3CL200808                   None       None
18       OC3CL200809                   None       None
19       OC3CL200011                  서울대공원
20       OC3CL200065                  서울대공원
21       OC3CL200140  서울특별시  강남구 일원동 246-13
22       V02Q1950001                   None       None
23       OT2CL200002                   None       None
24       V02Q1940922                   None       None

## 가정: 매핑되지 않은 25개 센서는 구형 스키마에 기록된 센서일 것이다
- 가정: 위경도정보 메타데이터 문서에 공시되지 않은 시리얼일 것이다.
- 결과: 꼭 그렇지는 않음 + 위치 정보 매핑이 잘 안 된 경우

In [9]:
query_old_schema_check = """
    WITH anomaly_sensors AS (
        SELECT 
            sensor_id_matched,
            address,
            SPLIT_PART(address, ' ', 2) AS district
        FROM v_sdot_final
        GROUP BY sensor_id_matched, address
        HAVING address IS NULL OR SPLIT_PART(address, ' ', 2) NOT LIKE '%구'
    )
    SELECT 
        a.sensor_id_matched,
        a.address,
        MIN(v.measure_timestamp) AS 최초_수집일,
        MAX(v.measure_timestamp) AS 최종_수집일,
        DATE_DIFF('day', MAX(v.measure_timestamp), CAST('2026-07-19' AS TIMESTAMP)) AS 수집중단_경과일
    FROM anomaly_sensors a
    JOIN v_sdot_final v ON a.sensor_id_matched = v.sensor_id_matched
    GROUP BY a.sensor_id_matched, a.address
    ORDER BY 최종_수집일 ASC
"""

df_old_schema_check = duckdb.sql(query_old_schema_check).pl()

print("📌 [이상치 25건 센서의 수집 기간 확인]")
display(df_old_schema_check)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

📌 [이상치 25건 센서의 수집 기간 확인]

shape: (25, 5)
┌───────────────────┬────────────────────┬───────────────────┬───────────────────┬─────────────────┐
│ sensor_id_matched ┆ address            ┆ 최초_수집일       ┆ 최종_수집일       ┆ 수집중단_경과일 │
│ ---               ┆ ---                ┆ ---               ┆ ---               ┆ ---             │
│ str               ┆ str                ┆ datetime[μs]      ┆ datetime[μs]      ┆ i64             │
╞═══════════════════╪════════════════════╪═══════════════════╪═══════════════════╪═════════════════╡
│ V02Q1940922       ┆ null               ┆ 2020-04-02        ┆ 2020-04-02        ┆ 2299            │
│                   ┆                    ┆ 17:00:00          ┆ 17:00:00          ┆                 │
│ V02Q1940963       ┆ null               ┆ 2020-04-02        ┆ 2020-04-03        ┆ 2298            │
│                   ┆                    ┆ 15:00:00          ┆ 11:00:00          ┆                 │
│ V02Q1940933       ┆ null               ┆ 2020-04-03        ┆ 2020-04-03        ┆ 2298            │
│                   ┆                    ┆ 16:00:00          ┆ 16:00:00          ┆                 │
│ V02Q1940982       ┆ null               ┆ 2020-04-01        ┆ 2020-04-03        ┆ 2298            │
│                   ┆                    ┆ 01:00:00          ┆ 17:00:00          ┆                 │
│ V02Q1940921       ┆ null               ┆ 2020-04-16        ┆ 2020-04-16        ┆ 2285            │
│                   ┆                    ┆ 13:00:00          ┆ 13:00:00          ┆                 │
│ …                 ┆ …                  ┆ …                 ┆ …                 ┆ …               │
│ OC3CL200010       ┆ 서울대공원         ┆ 2022-12-12        ┆ 2026-07-19        ┆ 0               │
│                   ┆                    ┆ 00:00:00          ┆ 15:07:00          ┆                 │
│ OC3CL200140       ┆ 서울특별시  강남구 ┆ 2021-11-09        ┆ 2026-07-19        ┆ 0               │
│                   ┆ 일원동 246-13      ┆ 00:00:00          ┆ 23:07:00          ┆                 │
│ OC3CL200065       ┆ 서울대공원         ┆ 2021-11-09        ┆ 2026-07-19        ┆ 0               │
│                   ┆                    ┆ 00:00:00          ┆ 23:07:00          ┆                 │
│ OC3CL200011       ┆ 서울대공원         ┆ 2021-11-09        ┆ 2026-07-19        ┆ 0               │
│                   ┆                    ┆ 00:00:00          ┆ 23:07:00          ┆                 │
│ OC3CL200061       ┆ 서울대공원         ┆ 2021-11-09        ┆ 2026-07-19        ┆ 0               │
│                   ┆                    ┆ 00:00:00          ┆ 23:07:00          ┆                 │
└───────────────────┴────────────────────┴───────────────────┴───────────────────┴─────────────────┘

### 위치 정보 다시 매핑

In [10]:
query_patch_view = """
    CREATE OR REPLACE VIEW v_sdot_final AS
    WITH mapped_data AS (
        SELECT 
            *,
            COALESCE(
                (SELECT 시리얼 FROM loc_table WHERE "변경 전 시리얼" = d.sensor_id OR "변경 전 시리얼(데이터 상 표기)" = d.sensor_id LIMIT 1), 
                sensor_id
            ) AS sensor_id_matched
        FROM v_sdot_clean d
    )
    SELECT 
        m.*,
        l.위도 AS lat,
        l.경도 AS lon,
        
        -- 1. 주소 텍스트 오타 및 예외 정제
        CASE 
            WHEN l.주소 LIKE '%  %' THEN REPLACE(l.주소, '  ', ' ')
            WHEN l.주소 = '서울대공원' THEN '경기도 과천시 서울대공원'
            ELSE l.주소 
        END AS address,
        
        -- 2. 공간 EDA를 위한 자치구(district) 파생 컬럼 아예 생성해두기
        CASE 
            WHEN l.주소 = '서울대공원' THEN '과천시'
            WHEN l.주소 IS NULL THEN '위치미상'
            ELSE SPLIT_PART(REPLACE(l.주소, '  ', ' '), ' ', 2)
        END AS district
        
    FROM mapped_data m
    LEFT JOIN loc_table l ON m.sensor_id_matched = l.시리얼
"""

# 뷰 업데이트 실행
duckdb.sql(query_patch_view)
print("✅ 주소 오타 및 예외 처리(서울대공원)가 반영된 v_sdot_final 뷰 업데이트 완료!\n")

# 검증 1: 보정 후 자치구별 센서 개수 다시 확인
query_verify_district = """
    SELECT 
        district AS 자치구,
        COUNT(DISTINCT sensor_id_matched) AS 고유_센서_수
    FROM v_sdot_final
    GROUP BY district
    ORDER BY 고유_센서_수 DESC
"""

df_verified = duckdb.sql(query_verify_district).pl()
print("📌 [검증 1: 보정 후 자치구별 센서 분포]")
display(df_verified)

print("-" * 50)

# 검증 2: 매핑 정합성 꼼꼼하게 최종 확인 (잔여 이상치 점검)
query_final_anomaly_check = """
    SELECT DISTINCT
        sensor_id_matched,
        address,
        district
    FROM v_sdot_final
    WHERE district NOT LIKE '%구' 
      AND district NOT IN ('과천시', '위치미상')
"""

df_final_anomaly = duckdb.sql(query_final_anomaly_check).pl()
print(f"🚨 [검증 2: 매핑 실패 잔여 이상치 총 {len(df_final_anomaly)}건]")

if len(df_final_anomaly) > 0:
    display(df_final_anomaly)
else:
    print("✅ 모든 데이터가 정상적인 '구', '과천시', 또는 '위치미상'으로 매핑되었습니다.")

✅ 주소 오타 및 예외 처리(서울대공원)가 반영된 v_sdot_final 뷰 업데이트 완료!

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

📌 [검증 1: 보정 후 자치구별 센서 분포]

shape: (27, 2)
┌──────────┬──────────────┐
│ 자치구   ┆ 고유_센서_수 │
│ ---      ┆ ---          │
│ str      ┆ i64          │
╞══════════╪══════════════╡
│ 마포구   ┆ 86           │
│ 양천구   ┆ 84           │
│ 강동구   ┆ 84           │
│ 성동구   ┆ 76           │
│ 관악구   ┆ 75           │
│ …        ┆ …            │
│ 성북구   ┆ 29           │
│ 용산구   ┆ 27           │
│ 금천구   ┆ 24           │
│ 위치미상 ┆ 20           │
│ 과천시   ┆ 4            │
└──────────┴──────────────┘

--------------------------------------------------

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

🚨 [검증 2: 매핑 실패 잔여 이상치 총 0건]
✅ 모든 데이터가 정상적인 '구', '과천시', 또는 '위치미상'으로 매핑되었습니다.

# Export to Parquet

In [11]:
import os

# --------------------------------------------------
# [3] v_sdot_final 뷰를 Parquet 파일로 추출 
# --------------------------------------------------
# 1. 저장할 경로 설정 (notebooks 폴더 기준 상위 디렉토리의 data/processed)
BASE_DIR = os.path.abspath('..')
SAVE_DIR = os.path.join(BASE_DIR, 'data', 'processed')

# 폴더가 없다면 안전하게 생성
os.makedirs(SAVE_DIR, exist_ok=True) 

# 최종 저장될 파일의 절대 경로
PARQUET_PATH = os.path.join(SAVE_DIR, 'sdot_final_mapped.parquet')

print(f"📂 저장 경로: {PARQUET_PATH}")
print("⏳ Parquet 파일로 추출 중입니다. 3,400만 건의 데이터라 약간의 시간이 소요될 수 있습니다...")

# 2. COPY 명령어를 사용하여 뷰의 결과를 Parquet 파일로 저장
query_export = f"""
    COPY (
        SELECT * FROM v_sdot_final
    ) TO '{PARQUET_PATH}' (FORMAT PARQUET);
"""
duckdb.sql(query_export)

print("✅ Parquet 파일 추출 완료!")

📂 저장 경로: /Users/gomdori/Documents/Git/sdot-analysis/data/processed/sdot_final_mapped.parquet
⏳ Parquet 파일로 추출 중입니다. 3,400만 건의 데이터라 약간의 시간이 소요될 수 있습니다...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✅ Parquet 파일 추출 완료!